### ISSUE TITLE
read out stack pointer and program counter

### ISSUE THREAD

**Issue by 2ni** [chris-heo/updizombie#1]
Hi Chris
I stumbled upon your code while trying to  set up a gdb server which should communicate with my attiny3217 over the serial port.
I already can start and stop it with updi commands (link.stcs).
I was wondering if you know how the stack pointer and program counter could be read. According to [microchips code](https://github.com/microchip-pic-avr-tools/pyedbglib/blob/5e0e9317baa751d4ead9aa9eb2403781f017151c/pyedbglib/protocols/avr8protocol.py#L38) they use the avr8 protocol command to read the CMD_AVR8_PC_READ and to read the stack pointer they do sth like:
```
AVR8_MEMTYPE_OCD = 0xD1
  memory_read(AVR8_MEMTYPE_OCD, 0x18, 0x02)
```

so I was wondering if I could simply do this:
```
link.key(updi.constants.UPDI_KEY_64, b'OCD     ')
print("0x%04x" % (link.ldcs(0x18)<<8 | link.ldcs(0x19))) // stack pointer
print(link.ldcs(updi.constants.CMD_AVR8_PC_READ)) // program counter (only 8bits?!?)
```

where/how did you find out about link.key("OCD.    ")?

**Comment by chris-heo** [comment]
Hi Denis,

I hooked up my trusty Saleae Logic analyzer to a setup with  the Atmel-ICE and wrote a simple (external) protocol analyzer in Python.
You can find it in this gist together with some sample data: https://gist.github.com/chris-heo/c01610dd33fe5bd6942db96105ad6fbb

I currently got no xmega2 setup ready but if you want I can put something together and provide the traces together with the data in Microchip studio.

Cheers, 
Chris

**Comment by 2ni** [comment]
Hi Chris
Many thanks for your quick answer. Unfortunately I have no atmel-ice, if you have time and like it would be nice to have a trace, if not I'll try to find out otherwise somehow...

**Comment by chris-heo** [comment]
Alright, I made a small test program, made a screen recording and captured some data for you:

https://user-images.githubusercontent.com/73906153/155809767-189c4f22-c1f3-4905-bb3a-933645cab2d1.mp4
[sppc.zip](https://github.com/chris-heo/updizombie/files/8145102/sppc.zip)

The logicdata file was created with Saleae Logic 1.2.29.
Hope this helps you.

Cheers,
Chris

**Comment by 2ni** [comment]
Many thx Chris, I'll have a look!
From a very 1st analysis it looks like the PC is read with
```

LDS from 0x0F94: 0x0060
```
and is effectively the value - 1. Which kinda would make sense, as PC always shows to the next command to execute. So they show the current PC of where the cursor is right now in atmel studio.

**Comment by chris-heo** [comment]
I think that's it. If you need some more info from the protocol, let me know. Else feel free to close this issue.

**Comment by 2ni** [comment]
I haven't checked in details yet, I could organize a pickit4 and with [pymcuprog](https://github.com/microchip-pic-avr-tools/pymcuprog) I can make specific calls such as get program counter and fetch the signal on the oscilloscope.
I should be able to confirm the findings then.
Nevertheless I close the "issue". Many thanks again for your (quick) help!

**Comment by chris-heo** [comment]
> and fetch the signal on the oscilloscope

If you want to do yourself a favor, get a simple Saleae clone (search for "24 MHz 8 Ch" on your preferred trading platform) and use it with sigrok/pulseview. Or just get an original Saleae, worth every cent!

**Comment by 2ni** [comment]
Thx for the hint. I have a picoscope which includes an analyzer and signal parsing.
Do you maybe know the settings of the updi? 2 stop bits, parity even, 8bits data doesn't seem to be right.
The signal I get on updi looks a bit odd

**Comment by chris-heo** [comment]
I used 8 bits, even parity, 1 stop bit for the analysis but it doesn't make a huge difference when analyzing (more when sending due to the longer holdoff time between bytes).

For confirmation: https://github.com/mraardvark/pyupdi/blob/4aa013e9ec4437af14af26189585ad594ab05164/updi/physical.py#L29

As example for the analysis:

8E2:
![grafik](https://user-images.githubusercontent.com/73906153/156435590-55d81028-6397-49b2-98f1-a1e1a6c01864.png)

8E1:
![grafik](https://user-images.githubusercontent.com/73906153/156435648-19591f5d-46ac-4d75-bfc8-0c5c0ff143d4.png)

Maybe a dumb error: is the Picoscope set to TTL UART or RS-232? latter is inverted.

**Comment by 2ni** [comment]
I can choose if trigger on rising or falling. That's how my signal looks like. If I only evaluate the signals in the middle which rises to ~3.3v I get sth more or less usable. But I don't see the value if the program counter I should get, eg 0x008f.
<img width="1672" alt="Screenshot 2022-03-02 at 21 20 11" src="https://user-images.githubusercontent.com/151210/156443326-718a6b91-586c-4e0d-afda-d87966724681.png">

**Comment by 2ni** [comment]
Got better values with 50kBd, 8 data, even parity, 2 stop bits. But the signal is still weird and the last part has always errors parsing.
<img width="1672" alt="Screenshot 2022-03-02 at 21 33 15" src="https://user-images.githubusercontent.com/151210/156444947-64701ea4-b279-4264-9b35-e915a147af55.png">

**Comment by chris-heo** [comment]
The 1st capture looks like garbled data - for that it would be interesting to see the individual bytes and how the decoder got triggered.
From the picoscope software it's not quite clear to what they refer "inverted" to as it depends on where you're coming from (UART or RS-232). Typically trying both and deciding on what looks more correct is a way ;)

The 2nd capture looks fine, you expect to see a lot of 0x55 as this is used to synchronize the frames.
I think it makes most sense to go and adapt the [updi traffic analyzer](https://gist.github.com/chris-heo/c01610dd33fe5bd6942db96105ad6fbb) to the export of the scope. Shouldn't be too much effort and clearly helps to understand what's going on there.
